# -*- coding: utf-8 -*-
DEPENDENCY_DISK_CACHE_VERSION="depmap-3f-parent-int32-v1"
DEPENDENCY_LEGACY_DISK_CACHE_VERSION="depmap-3d-pickle-v1"
DEPENDENCY_PARENT_MAGIC=b"DP3F_PARENT_I32_V1\x00"
DEPENDENCY_CACHE_PRELOAD_BATCH_SIZE=500
